// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Movie struct {
	ID      string    `json:"id"`
	Title   string    `json:"title"`
	Reviews []*Review `json:"reviews"`
}

type MovieInput struct {
	ID    *string `json:"id,omitempty"`
	Title string  `json:"title"`
}

type Mutation struct {
}

type Query struct {
}

type Review struct {
	ID      string `json:"id"`
	Stars   int32  `json:"stars"`
	Comment string `json:"comment"`
	Movie   *Movie `json:"movie"`
}

type ReviewInput struct {
	Stars   int32  `json:"stars"`
	Comment string `json:"comment"`
}
