mongo:
  replicaCount: 1
  image:
    repository: mongo
    tag: 5.0
  service:
    type: ClusterIP
    port: 27017
  secret:
    name: mongo-secret
    userKey: mongo-user
    passwordKey: mongo-password

image:
  replicaCount: 1
  image:
    repository: jusjira/k8s-demo-svelte-webapp
    tag: v1.1
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
    nodePort: 30100
  env:
    secret:
      name: mongo-secret
      userKey: mongo-user
      passwordKey: mongo-password
    configMap:
      name: mongo-config
      urlKey: mongo-url

service:
  nodePort: 30200
  port: 30000
  protocol: TCP
  targetPort: 30000
  type: NodePort

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi

serviceAccount:
  create: true

autoscaling:
  enabled: true
  maxReplicas: 5

replicaCount:
  webapp: 1
  mongo: 1

ingress:
  enabled: false
  hostname: webapp.example.com
  path: /

persistence:
  enabled: false


httpRoute:
  # HTTPRoute enabled.
  enabled: false
  # HTTPRoute annotations.
  annotations: {}
  # Which Gateways this Route is attached to.
  parentRefs:
  - name: gateway
    sectionName: http
    # namespace: default
  # Hostnames matching HTTP header.
  hostnames:
  - chart-example.local
  # List of rules and filters applied.
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /headers
  #   filters:
  #   - type: RequestHeaderModifier
  #     requestHeaderModifier:
  #       set:
  #       - name: My-Overwrite-Header
  #         value: this-is-the-only-value
  #       remove:
  #       - User-Agent
  # - matches:
  #   - path:
  #       type: PathPrefix
  #       value: /echo
  #     headers:
  #     - name: version
  #       value: v2